# Dutch Menu

[[main]]
  identifier = "Automatiseringen"
  name = "Automatizáció"
  url = "/"
  weight = 1

[[main]]
  identifier = "development"
  name = "MKB Oplossingen"
  url = "/sme-solutions"
  weight = 2

[[main]]
  identifier = "business"
  name = "Enterprise Oplossingen"
  url = "/business/"
  weight = 3

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 4
